% make metadata (steps, param, and updated parquet) for summary files lili generates. 

% To use, add dataset names to the 'datasets' variable in which ever
% section, and run sections to preprocess the datasets. 

clear all; close all; 

%% intact + offball datasets

%%% FECO DATASETS %%%
datasets = {'iav_activation_intact_offball', ... 
            'split_half_control_activation_intact_offball', ... 
            'claw_flexion_activation_intact_offball', ... 
            'claw_extension_activation_intact_offball', ... 
            'hook_flexion_activation_intact_offball', ... 
            'hook_extension_activation_intact_offball', ... 
            'club_JR175_activation_intact_offball', ... 
            'club_JR299_activation_intact_offball', ... 
            'iav_silencing_intact_offball', ... 
            'claw_flexion_silencing_intact_offball', ... 
            'claw_extension_silencing_intact_offball', ... 
            'hook_flexion_silencing_intact_offball', ... 
            'hook_extension_silencing_intact_offball', ... 
            'club_JR175_silencing_intact_offball', ... 
            'club_JR299_silencing_intact_offball', ... 
            'split_half_control_silencing_intact_offball'};
%%%%%%%%%%%%%%%%%%%%%%%%

fprintf('\n\nProcessing intact + offball datasets...'); 

initial_vars = who; 
initial_vars{end+1} = 'd';

for d = 1:width(datasets)
    clearvars('-except',initial_vars{:}); initial_vars = who;
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_headless_and_offball_fn(dataset);
end
clear all; close all; 

fprintf('\nDone processing intact + offball datasets!\n');

%% headless + onball datasets

% %%% FECO DATASETS %%%
% datasets = {'iav_activation_headless_onball', ... 
%             'split_half_control_activation_headless_onball', ... 
%             'claw_flexion_activation_headless_onball', ... 
%             'claw_extension_activation_headless_onball', ... 
%             'hook_flexion_activation_headless_onball', ... 
%             'hook_extension_activation_headless_onball', ... 
%             'club_JR175_activation_headless_onball', ... 
%             'club_JR299_activation_headless_onball', ... 
%             'iav_silencing_headless_onball', ... 
%             'claw_flexion_silencing_headless_onball', ... 
%             'claw_extension_silencing_headless_onball', ... 
%             'hook_flexion_silencing_headless_onball', ... 
%             'hook_extension_silencing_headless_onball', ... 
%             'club_JR175_silencing_headless_onball', ... 
%             'club_JR299_silencing_headless_onball', ... 
%             'split_half_control_silencing_headless_onball'};
% %%%%%%%%%%%%%%%%%%%%%%%%

%%% HAIR PLATE DATASETS %%%
datasets = {'R48A07AD;R20C06DBD_silencing_headless_onball', ...
            'R48A07AD;R20C06DBD_activation_headless_onball', ...
            'hair_plate_split_half_control_silencing_headless_onball', ...
            'hair_plate_split_half_control_activation_headless_onball'};
%%%%%%%%%%%%%%%%%%%%%%%%

initial_vars = who; 
initial_vars{end+1} = 'd';

fprintf('\n\nProcessing headless + onball datasets...'); 

for d = 1:width(datasets)
    clearvars('-except',initial_vars{:}); initial_vars = who;
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_headless_and_offball_fn(dataset);
end
clear all; close all; 

fprintf('\nDone processing headless + onball datasets!\n'); 

%% headless + offball datasets

%%% FECO DATASETS %%%
datasets = {'iav_activation_headless_offball', ... 
            'claw_flexion_activation_headless_offball', ... 
            'claw_extension_activation_headless_offball', ... 
            'hook_flexion_activation_headless_offball', ... 
            'hook_extension_activation_headless_offball', ... 
            'club_JR175_activation_headless_offball', ... 
            'club_JR299_activation_headless_offball', ... 
            'split_half_control_activation_headless_offball', ... 
            'iav_silencing_headless_offball', ... 
            'claw_flexion_silencing_headless_offball', ... 
            'claw_extension_silencing_headless_offball', ... 
            'hook_flexion_silencing_headless_offball', ... 
            'hook_extension_silencing_headless_offball', ... 
            'club_JR175_silencing_headless_offball', ... 
            'club_JR299_silencing_headless_offball', ... 
            'split_half_control_silencing_headless_offball'};
%%%%%%%%%%%%%%%%%%%%%%%%

initial_vars = who; 
initial_vars{end+1} = 'd';

fprintf('\n\nProcessing headless + offball datasets...'); 

for d = 1:width(datasets)
    clearvars('-except',initial_vars{:}); initial_vars = who;
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_headless_and_offball_fn(dataset);
end
clear all; close all; 

fprintf('\nDone processing headless + offball datasets!\n'); 

%% intact + onball datasets

% %%% FECO DATASETS %%%
% datasets = {'iav_activation_intact_onball', ... 
%             'claw_flexion_activation_intact_onball', ... 
%             'claw_extension_activation_intact_onball', ... 
%             'hook_flexion_activation_intact_onball', ... 
%             'hook_extension_activation_intact_onball', ... 
%             'club_JR175_activation_intact_onball', ... 
%             'club_JR299_activation_intact_onball', ... 
%             'split_half_control_activation_intact_onball', ... 
%             'iav_silencing_intact_onball', ... 
%             'claw_flexion_silencing_intact_onball', ... 
%             'claw_extension_silencing_intact_onball', ... 
%             'hook_flexion_silencing_intact_onball', ... 
%             'hook_extension_silencing_intact_onball', ... 
%             'club_JR175_silencing_intact_onball', ... 
%             'club_JR299_silencing_intact_onball', ... 
%             'split_half_control_silencing_intact_onball', ... 
%             'split_half_control_all_intact_onball'}; 
% %%%%%%%%%%%%%%%%%%%%%%%

%%% HAIR PLATE DATASETS %%%
datasets = {'R48A07AD;R20C06DBD_silencing_intact_onball', ...
            'R48A07AD;R20C06DBD_activation_intact_onball', ...
            'hair_plate_split_half_control_silencing_intact_onball', ...
            'hair_plate_split_half_control_activation_intact_onball'};

%%%%%%%%%%%%%%%%%%%%%%%%

initial_vars = who; 
initial_vars{end+1} = 'd';

fprintf('\n\nProcessing intact + onball datasets...'); 

for d = 1:width(datasets)
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_intact_onball_fn(dataset);
    clearvars('-except',initial_vars{:}); initial_vars = who;
end
clear all; close all; 

fprintf('\nDone processing intact + onball datasets!\n'); 

%% intact + onball + pwr datasets

%                       ACTIVATION 
clear all; close all; 

%%% FECO DATASETS %%%
datasets = {'iav_activation_intact_onball_laser_power', ... 
            'claw_flexion_activation_intact_onball_laser_power', ... 
            'claw_extension_activation_intact_onball_laser_power', ... 
            'hook_flexion_activation_intact_onball_laser_power', ... 
            'hook_extension_activation_intact_onball_laser_power', ... 
            'club_JR175_activation_intact_onball_laser_power', ... 
            'club_JR299_activation_intact_onball_laser_power', ... 
            'split_half_control_activation_intact_onball_laser_power'};
%%%%%%%%%%%%%%%%%%%%%%%%

initial_vars = who; 
initial_vars{end+1} = 'd';

fprintf('\n\nProcessing intact + onball + power activation datasets...'); 

for d = 1:width(datasets)
    clearvars('-except',initial_vars{:}); initial_vars = who;
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_intact_onball_fn(dataset);

end
clear all; close all; 

fprintf('\nDone processing intact + onball + power activation datasets!\n'); 


clear all; close all; 

%                       SILENCING 

%%% FECO DATASETS %%%
datasets = {'claw_flexion_silencing_intact_onball_laser_power', ... 
            'claw_extension_silencing_intact_onball_laser_power', ... 
            'hook_flexion_silencing_intact_onball_laser_power', ... 
            'hook_extension_silencing_intact_onball_laser_power', ... %NOT PROCESSED (file doesn't exist)
            'iav_silencing_intact_onball_laser_power', ... %NOT PROCESSED (error thrown) 
            'club_JR175_silencing_intact_onball_laser_power', ... 
            'club_JR299_silencing_intact_onball_laser_power', ... 
            'split_half_control_silencing_intact_onball_laser_power'}; 
%%%%%%%%%%%%%%%%%%%%%%%%

initial_vars = who; 
initial_vars{end+1} = 'd';

fprintf('\n\nProcessing intact + onball + power silencing datasets...'); 

for d = 1:width(datasets)
    clearvars('-except',initial_vars{:}); initial_vars = who;
    dataset = datasets{d};
    fprintf(['\n' dataset ' (' num2str(d) '/' num2str(width(datasets)) ')']);

    %generate and save metadata
    make_metadata_intact_onball_fn(dataset);

end
clear all; close all; 

fprintf('\nDone processing intact + onball + power silencing datasets!\n'); 
