function [data, path] = DLC_extract_parquet(varargin)

% [data, columns, column_names] = DLC_extract_parquet(root, file);
% [data, columns, column_names] = DLC_extract_parquet(path);
% Arguments: 
% root --> the location of the folder housing the parquet file
%             ex: 'G:\My Drive\Pierre\summaries\v3\lines\'
% file --> parquet file
%             ex: 'sarah--rv3-ClawFlexion&Extension-JR688-gal4xUAS-10x-ChrimsonR-headless.pq'
% path --> fill path to parquet file
%             ex: 'G:\My Drive\Pierre\summaries\v3\lines\sarah--rv3-ClawFlexion&Extension-JR688-gal4xUAS-10x-ChrimsonR-headless.pq'
% 
% S Walling-Bell
% University of Washington, 2020

% % -- Extract contents of parquet file -- % %


    if nargin == 1
        path = varargin{1};
    elseif nargin == 2
        path = join([varargin{1}, varargin{2}]);  
    end
    
% % COLUMNS FOR V3-B3 PARQUET FILES:
%     columns = {'standing_prob', 'standing_bout_number',...
%     'walking_prob',             'walking_bout_number',...
%     'abdomen_grooming_prob',    'abdomen_grooming_bout_number',...
%     'air_legs_prob',            'air_legs_bout_number',...
%     'antennae_grooming_prob',   'antennae_grooming_bout_number',...
%     'ball_push_prob',           'ball_push_bout_number',...
%     'ball_tapping_prob',        'ball_tapping_bout_number',...
%     'crabwalking_prob',         'crabwalking_bout_number',...
%     'egg_laying_prob',          'egg_laying_bout_number',...
%     'head/eye_grooming_prob',   'head/eye_grooming_bout_number',...
%     'mouth_grooming_prob',      'mouth_grooming_bout_number',...
%     'other_prob',               'other_bout_number',...
%     'postural_adjustment_prob', 'postural_adjustment_bout_number',...
%     't1_grooming_prob',         't1_grooming_bout_number',...
%     't1_t2_grooming_prob',      't1_t2_grooming_bout_number',...
%     't3_grooming_prob',         't3_grooming_bout_number',...
%     'folder_1', 'filename', 'fnum', 'date_parsed', 'flyid', 'fly', 'date', 'rep', 'condnum', 'type', 'dir', 'stimlen',... 
%     'pipeline_version', 'Fly Line', 'Sex', 'Head', 'Ball', 'Stimulus Procedure', 'Basler length', 'LED color', 'LED intensity', 'LED length', 'Temp', 'Humidity', 'Tether', 'Fly Age',...
%     'temp',...
%     'fictrac_frame_counter', 'fictrac_delta_rot_cam_x', 'fictrac_delta_rot_cam_y', 'fictrac_delta_rot_cam_z',...
%     'fictrac_delta_rot_score', 'fictrac_delta_rot_lab_x', 'fictrac_delta_rot_lab_y', 'fictrac_delta_rot_lab_z',...
%     'fictrac_sphere_orientation_cam_x', 'fictrac_sphere_orientation_cam_y', 'fictrac_sphere_orientation_cam_z',...
%     'fictrac_sphere_orientation_lab_x', 'fictrac_sphere_orientation_lab_y', 'fictrac_sphere_orientation_lab_z', ...
%     'fictrac_int_x', 'fictrac_int_y', 'fictrac_heading', 'fictrac_inst_dir', 'fictrac_speed', 'fictrac_int_forward',...
%     'fictrac_int_side', 'fictrac_timestamp', 'fictrac_seqnumber', ...
%     'L1_BC', 'L1_CF', 'L1_FTi', 'L1_TiTa',...
%     'L2_BC', 'L2_CF', 'L2_FTi', 'L2_TiTa',...
%     'L3_BC', 'L3_CF', 'L3_FTi', 'L3_TiTa',...
%     'R1_BC', 'R1_CF', 'R1_FTi', 'R1_TiTa',...
%     'R2_BC', 'R2_CF', 'R2_FTi', 'R2_TiTa',...
%     'R3_BC', 'R3_CF', 'R3_FTi', 'R3_TiTa',...
%     'L1A_abduct', 'L1A_flex', 'L1A_rot', 'L1B_flex', 'L1B_rot', 'L1C_flex', 'L1C_rot', 'L1D_flex',...
%     'L2A_abduct', 'L2A_flex', 'L2A_rot', 'L2B_flex', 'L2B_rot', 'L2C_flex', 'L2C_rot', 'L2D_flex',...
%     'L3A_abduct', 'L3A_flex', 'L3A_rot', 'L3B_flex', 'L3B_rot', 'L3C_flex', 'L3C_rot', 'L3D_flex',...
%     'R1A_abduct', 'R1A_flex', 'R1A_rot', 'R1B_flex', 'R1B_rot', 'R1C_flex', 'R1C_rot', 'R1D_flex',...
%     'R2A_abduct', 'R2A_flex', 'R2A_rot', 'R2B_flex', 'R2B_rot', 'R2C_flex', 'R2C_rot', 'R2D_flex',...
%     'R3A_abduct', 'R3A_flex', 'R3A_rot', 'R3B_flex', 'R3B_rot', 'R3C_flex', 'R3C_rot', 'R3D_flex',...
%     'L1A_x', 'L1A_y', 'L1A_z', 'L1B_x', 'L1B_y', 'L1B_z', 'L1C_x', 'L1C_y', 'L1C_z', 'L1D_x', 'L1D_y', 'L1D_z', 'L1E_x', 'L1E_y', 'L1E_z',...
%     'L2A_x', 'L2A_y', 'L2A_z', 'L2B_x', 'L2B_y', 'L2B_z', 'L2C_x', 'L2C_y', 'L2C_z', 'L2D_x', 'L2D_y', 'L2D_z', 'L2E_x', 'L2E_y', 'L2E_z',...
%     'L3A_x', 'L3A_y', 'L3A_z', 'L3B_x', 'L3B_y', 'L3B_z', 'L3C_x', 'L3C_y', 'L3C_z', 'L3D_x', 'L3D_y', 'L3D_z', 'L3E_x', 'L3E_y', 'L3E_z',...
%     'R1A_x', 'R1A_y', 'R1A_z', 'R1B_x', 'R1B_y', 'R1B_z', 'R1C_x', 'R1C_y', 'R1C_z', 'R1D_x', 'R1D_y', 'R1D_z', 'R1E_x', 'R1E_y', 'R1E_z',...
%     'R2A_x', 'R2A_y', 'R2A_z', 'R2B_x', 'R2B_y', 'R2B_z', 'R2C_x', 'R2C_y', 'R2C_z', 'R2D_x', 'R2D_y', 'R2D_z', 'R2E_x', 'R2E_y', 'R2E_z',...
%     'R3A_x', 'R3A_y', 'R3A_z', 'R3B_x', 'R3B_y', 'R3B_z', 'R3C_x', 'R3C_y', 'R3C_z', 'R3D_x', 'R3D_y', 'R3D_z', 'R3E_x', 'R3E_y', 'R3E_z'};
% 
% 

% COLUMNS FOR V3-B4 PARQUET FILES:
    columns = {'standing_prob', 'standing_bout_number',...
    'walking_prob',             'walking_bout_number',...
    'abdomen_grooming_prob',    'abdomen_grooming_bout_number',...
    'air_legs_prob',            'air_legs_bout_number',...
    'antennae_grooming_prob',   'antennae_grooming_bout_number',...
    'ball_push_prob',           'ball_push_bout_number',...
    'ball_tapping_prob',        'ball_tapping_bout_number',...
    'crabwalking_prob',         'crabwalking_bout_number',...
    'egg_laying_prob',          'egg_laying_bout_number',...
    'head/eye_grooming_prob',   'head/eye_grooming_bout_number',...
    'mouth_grooming_prob',      'mouth_grooming_bout_number',...
    'other_prob',               'other_bout_number',...
    'postural_adjustment_prob', 'postural_adjustment_bout_number',...
    't1_grooming_prob',         't1_grooming_bout_number',...
    't1_t2_grooming_prob',      't1_t2_grooming_bout_number',...
    't3_grooming_prob',         't3_grooming_bout_number',...
    'folder_1', 'filename', 'fnum', 'date_parsed', 'flyid', 'fly', 'date', 'rep', 'condnum', 'type', 'dir', 'stimlen',... 
    'pipeline_version', 'Fly Line', 'Sex', 'Head', 'Ball', 'Stimulus Procedure', 'Basler length', 'LED color', 'LED intensity', 'LED length', 'Temp', 'Humidity', 'Tether', 'Fly Age',...
    'temp', ...
    'fictrac_frame_counter','fictrac_delta_rot_cam_x','fictrac_delta_rot_cam_y','fictrac_delta_rot_cam_z', ...
    'fictrac_delta_rot_score','fictrac_delta_rot_lab_x','fictrac_delta_rot_lab_y','fictrac_delta_rot_lab_z', ...
    'fictrac_sphere_orientation_cam_x','fictrac_sphere_orientation_cam_y','fictrac_sphere_orientation_cam_z', ...
    'fictrac_int_x', 'fictrac_int_y','fictrac_heading', 'fictrac_inst_dir','fictrac_speed', 'fictrac_int_forward', ...
    'fictrac_int_side', 'fictrac_timestamp','fictrac_seqnumber', 'starts', ...
    'fictrac_delta_rot_lab_x_mms','fictrac_delta_rot_lab_y_mms','fictrac_delta_rot_lab_z_mms', ...
    'fictrac_speed_mms','fictrac_inst_dir_deg','fictrac_heading_deg','fictrac_int_forward_mm', ...
    'fictrac_int_side_mm', 'fictrac_int_x_mm','fictrac_int_y_mm', ...
    'L1_BC', 'L1_CF', 'L1_FTi', 'L1_TiTa',...
    'L2_BC', 'L2_CF', 'L2_FTi', 'L2_TiTa',...
    'L3_BC', 'L3_CF', 'L3_FTi', 'L3_TiTa',...
    'R1_BC', 'R1_CF', 'R1_FTi', 'R1_TiTa',...
    'R2_BC', 'R2_CF', 'R2_FTi', 'R2_TiTa',...
    'R3_BC', 'R3_CF', 'R3_FTi', 'R3_TiTa',...
    'L1A_abduct', 'L1A_flex', 'L1A_rot', 'L1B_flex', 'L1B_rot', 'L1C_flex', 'L1C_rot', 'L1D_flex',...
    'L2A_abduct', 'L2A_flex', 'L2A_rot', 'L2B_flex', 'L2B_rot', 'L2C_flex', 'L2C_rot', 'L2D_flex',...
    'L3A_abduct', 'L3A_flex', 'L3A_rot', 'L3B_flex', 'L3B_rot', 'L3C_flex', 'L3C_rot', 'L3D_flex',...
    'R1A_abduct', 'R1A_flex', 'R1A_rot', 'R1B_flex', 'R1B_rot', 'R1C_flex', 'R1C_rot', 'R1D_flex',...
    'R2A_abduct', 'R2A_flex', 'R2A_rot', 'R2B_flex', 'R2B_rot', 'R2C_flex', 'R2C_rot', 'R2D_flex',...
    'R3A_abduct', 'R3A_flex', 'R3A_rot', 'R3B_flex', 'R3B_rot', 'R3C_flex', 'R3C_rot', 'R3D_flex',...
    'L1A_x', 'L1A_y', 'L1A_z', 'L1B_x', 'L1B_y', 'L1B_z', 'L1C_x', 'L1C_y', 'L1C_z', 'L1D_x', 'L1D_y', 'L1D_z', 'L1E_x', 'L1E_y', 'L1E_z',...
    'L2A_x', 'L2A_y', 'L2A_z', 'L2B_x', 'L2B_y', 'L2B_z', 'L2C_x', 'L2C_y', 'L2C_z', 'L2D_x', 'L2D_y', 'L2D_z', 'L2E_x', 'L2E_y', 'L2E_z',...
    'L3A_x', 'L3A_y', 'L3A_z', 'L3B_x', 'L3B_y', 'L3B_z', 'L3C_x', 'L3C_y', 'L3C_z', 'L3D_x', 'L3D_y', 'L3D_z', 'L3E_x', 'L3E_y', 'L3E_z',...
    'R1A_x', 'R1A_y', 'R1A_z', 'R1B_x', 'R1B_y', 'R1B_z', 'R1C_x', 'R1C_y', 'R1C_z', 'R1D_x', 'R1D_y', 'R1D_z', 'R1E_x', 'R1E_y', 'R1E_z',...
    'R2A_x', 'R2A_y', 'R2A_z', 'R2B_x', 'R2B_y', 'R2B_z', 'R2C_x', 'R2C_y', 'R2C_z', 'R2D_x', 'R2D_y', 'R2D_z', 'R2E_x', 'R2E_y', 'R2E_z',...
    'R3A_x', 'R3A_y', 'R3A_z', 'R3B_x', 'R3B_y', 'R3B_z', 'R3C_x', 'R3C_y', 'R3C_z', 'R3D_x', 'R3D_y', 'R3D_z', 'R3E_x', 'R3E_y', 'R3E_z'};


    for j = 1:width(columns)
        column_names{j} = strrep(columns{j}, '_', '-');
    end

%     info = parquetinfo(path); % info.VariableNames to see column names 
%     sum(contains(info.VariableNames, 'flex')); % shows if string is part of any var name
%     find(contains(info.VariableNames, 'velocity')); %shows which column contains string in var name
% 
%TODO uncomment these lines to be able to load multple files and with selected columns. 
% data = [];
% for file = 1:width(path)
%     data = [data; parquetread(path{file}, 'SelectedVariableNames', columns)];
% end

% % TODO uncomment this line to load all of one file. 
data = [];
for file = 1:width(path)
     data = parquetread(path{1}); %read in all the data. 
end

end